### ISSUE TITLE
Put compiled json under folder artifacts/

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/tic-tac-toe#16]
Should NOT be in contracts/ folder
https://github.com/sCrypt-Inc/tic-tac-toe/blob/4a8581370551662b30fe289e9a887b9b5a99afe5/src/index.tsx#L9

Update
https://learn.scrypt.io/en/courses/Build-a-Tic-tac-toe-Game-with-sCrypt-614c387bc0974f55df5af1e5/lessons/2/chapters/1

> where the contract is located

**Comment by xhliu** [comment]
Make it same w/ Eth project. Put all compiled results under one folder.
![image](https://user-images.githubusercontent.com/1017252/218605127-f4f8c9c8-04d6-4b27-acef-755cf720decd.png)

**Comment by zhfnjust** [comment]
need to change the webpack config.
