### ISSUE TITLE
use "fill" and CTC

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/tic-tac-toe#19]
fill(EMPTY, N)

`this.board = [0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n];`

**Comment by zhfnjust** [comment]
fixed f098108b11e54428f37e2814992ca9f4385a89de

**Comment by xhliu** [comment]
Did u also update js in Learn?
`states.instance.board = [0,0,0,0,0,0,0,0,0];`

Also use CTC, instead of 9.

**Comment by xhliu** [comment]
@zhfnjust

**Comment by zhfnjust** [comment]
use fill now. and learn updated:

We have discussed before, don’t introduce him to CTC here to prevent the course from becoming complicated.


![Image](https://user-images.githubusercontent.com/995909/222186357-65be7742-e01e-435c-be3a-aa375a2e7449.png)
