### ISSUE TITLE
Fix Learn

### ISSUE THREAD

**Issue by gitzhou** [sCrypt-Inc/tic-tac-toe#21]
- [x] paste complete code in chapters 
- [x] .gitignore `artifact` -> `artifacts`
- [x] `balance` -> `aliceBalance`
- [x] Import

**Comment by gitzhou** [comment]
<img width="631" alt="CleanShot-2023-03-13-07-22-14" src="https://user-images.githubusercontent.com/1585505/224580242-99125867-8629-42af-aaba-3b65df0e5213.png">

**Comment by gitzhou** [comment]
change to use `requestAuthorization`

```ts
const { isAuthorized, error } = await signer.requestAuthorization()
if (!isAuthorized) {
  throw new Error(error)
}
```

**Comment by xhliu** [comment]
https://github.com/sCrypt-Inc/learn-scrypt-courses/issues/26
