### ISSUE TITLE
Fresh clone and local install fails with &#x27;Calling function which returns &#x60;any&#x60; is not allowed&#x27;

### ISSUE THREAD

**Issue by hjvogel** [sCrypt-Inc/tic-tac-toe#27]
npx scrypt-cli compile
Need to install the following packages:
scrypt-cli@0.1.73
Ok to proceed? (y) y
⠋ Building TS...
scrypt-ts ERROR - ../Git/tic-tac-toe/src/contracts/tictactoe.ts:50:54:50:61 - Calling function which returns `any` is not allowed

npx -v
10.2.4

**Comment by hjvogel** [comment]
Figured out from the github deploy workflow if run

npm cli

npm run build:contract

npm start 

it brings it up and running on localhost , but server full of warnings:

WARNING in ./node_modules/scryptlib/dist/utils.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '..\Git\tic-tac-toe\node_modules\scryptlib\dist\utils.js.map' file: Error: ENOENT: no such file or directory, open '..\Git\tic-tac-toe\node_modules\scryptlib\dist\utils.js.map'

also npm run build did not help here...

Finally, cannot connet to the Yours wallet (rename TBD from Panda) , despite the Yours popup comes up and connec could be clicked

**Comment by hjvogel** [comment]
After I had to remove some odd other extension - I got yours to run.

I switched to testnet and went to the https://scrypt.io/faucet got few testnet sats.


But on click start  butoon - I got:

Deploying TicTacToe failed. TypeError: tx._getUnspentValue is not a function
    at checkTxFee (index.js:83:1)
    at SmartContract.<anonymous> (contract.js:1920:1)
    at Generator.next (<anonymous>)
    at contract.js:31:1
    at new Promise (<anonymous>)
    at __webpack_modules__../node_modules/scrypt-ts/dist/smart-contract/contract.js.__awaiter (contract.js:27:1)
    at SmartContract.autoPayfee (contract.js:1919:1)
    at TicTacToe.<anonymous> (contract.js:1026:1)
    at Generator.next (<anonymous>)
    at fulfilled (contract.js:28:1)

**Comment by msinkec** [comment]
What version of `typescript` and `scrypt-ts` are you using?

**Comment by hjvogel** [comment]
It managed to compile just with node v20 - but after 

npm install -D typescript

it works now
